service: fast-api
runtime: python312

instance_class: F2
env_variables:
  APP_ENV: 'production'

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b :$PORT main:app

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 10

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

